# Generated by Django 5.2.17 on 2026-09-19 22:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=12)),
                ('reviewed_count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'recorded_on'],
            },
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('flashcard', 'Flashcard'), ('case', 'Clinical case'), ('quiz', 'Quiz')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Study activity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_goal', models.PositiveIntegerField(default=20)),
                ('daily_completed', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('total_cards_reviewed', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('total_hours_studied', models.FloatField(default=0.0)),
                ('cards_retention_rate', models.FloatField(default=0.0)),
                ('clinical_case_success_rate', models.FloatField(default=0.0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=120)),
                ('mastery_percent', models.PositiveSmallIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subject mastery',
                'ordering': ['-mastery_percent'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
