# Generated by Django 5.2.17 on 2026-09-19 22:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(db_index=True, max_length=120)),
                ('presenting_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('final_diagnosis', models.CharField(max_length=250)),
                ('discussion', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vignette', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=120)),
                ('yield_rating', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10)),
                ('block', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['subject', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DifferentialDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.CharField(max_length=250)),
                ('correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentials', to='study.clinicalcase')),
            ],
            options={
                'ordering': ['order', 'diagnosis'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vignette', models.TextField()),
                ('diagnosis', models.CharField(max_length=300)),
                ('rationale', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=120)),
                ('difficulty', models.CharField(blank=True, choices=[('Again', 'Again'), ('Hard', 'Hard'), ('Good', 'Good'), ('Easy', 'Easy')], max_length=10, null=True)),
                ('interval_days', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flashcards', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.deck')),
            ],
            options={
                'ordering': ['next_review_date', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('Again', 'Again'), ('Hard', 'Hard'), ('Good', 'Good'), ('Easy', 'Easy')], max_length=10)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_after', models.FloatField(default=1.0)),
                ('ease_after', models.FloatField(default=2.5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study.flashcard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=80)),
                ('reference_range', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='study.clinicalcase')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.TextField(blank=True)),
                ('vitals', models.TextField(blank=True)),
                ('cardiovascular', models.TextField(blank=True)),
                ('respiratory', models.TextField(blank=True)),
                ('abdomen', models.TextField(blank=True)),
                ('neurological', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_exam', to='study.clinicalcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study.quizquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
