# Generated by Django 5.2.17 on 2026-09-19 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalcase',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CaseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-progress', 'In progress'), ('completed', 'Completed')], default='available', max_length=20)),
                ('completed_steps', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveSmallIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='study.clinicalcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Case progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
